### ISSUE TITLE
off by one error for logos vs links on purchase page

### ISSUE THREAD

**Issue by aaronmgdr** [Open-C/celohub#2]
On https://celohub.org/purchase if i hover over any link the logo does not match the destination

for example 
Logo "wyre",  link bitrex, 
logo bitgo, link sendwyre
logo valora, link moonpay
etc

**Comment by aaronmgdr** [comment]
looks like the alt text for images matches the link

**Comment by 0xhuman** [comment]
Hey Aaron, thanks for pointing this out! Looks like one of our columns was accidentally offset by a cell. We will push an update momentarily to fix this :)
