### ISSUE TITLE
The documentation for Valora is pointing to the wrong or deprecated URL

### ISSUE THREAD

**Issue by lopeselio** [Open-C/celohub#5]
I was studying about Valora from the Celo Hub. I have noticed that the URL for the Valora wallet documentation is pointing out to the wrong destination, after clicking on the Github icon on celo Hub
[wrong destination](https://github.com/celo-org/celo-monorepo/tree/master/packages/mobile)

![image](https://user-images.githubusercontent.com/43913734/123747413-8d477600-d8d0-11eb-9fbc-313fb264dc85.png)

Can we have it updated so that we find the exact location to the documentation of the valora wallet ?
![image](https://user-images.githubusercontent.com/43913734/123747529-b1a35280-d8d0-11eb-9708-e807c8b978a4.png)

**Comment by lopeselio** [comment]
@0xhuman @darrylyeo @annakaz , I am guessing this is the correct URL:
[Correct URL](https://github.com/celo-org/wallet)

Thanks and Cheers
Elio
Celo India Fellow

**Comment by 0xhuman** [comment]
Hey @lopeselio sorry for the late reply here. Luckily we fixed this a while back. Thanks for pointing it out!

**Comment by lopeselio** [comment]
you're welcome
